# Generated by Django 5.2.7 on 2025-10-20 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocr', '0002_alter_ocrdocument_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatterRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('model', models.CharField(default='gpt-4o-mini', max_length=255)),
                ('status', models.CharField(choices=[('in_queue', 'In Queue'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_queue', max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('output_markdown', models.FileField(blank=True, null=True, upload_to='formatter/output_markdown/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocr_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatter_runs', to='ocr.ocrdocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatter_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormatterChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(help_text="e.g. '1-3,5'", max_length=255)),
                ('input_chars', models.IntegerField(default=0)),
                ('output_markdown', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='formatter.formatterrun')),
            ],
        ),
    ]
