# Generated by Django 5.2.7 on 2025-10-19 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.TextField()),
                ('prompt', models.TextField()),
                ('model', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=800)),
                ('request_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('response_md', models.TextField(blank=True, null=True)),
                ('input_tokens_est', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cached_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
