# Generated by Django 5.2.7 on 2025-10-19 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_range', models.CharField(blank=True, help_text="e.g. 'all', '1-10', '1,3,5-7', '1-3,5'", max_length=100)),
                ('languages', models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('en-hi', 'English Hindi')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to='uploads.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='OCRPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('pdf_text', 'Pdf Text'), ('ocr', 'Ocr')], max_length=10)),
                ('text', models.TextField()),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.ocrdocument')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
