# Generated by Django 5.2.7 on 2025-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrdocument',
            name='languages',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('hin', 'Hindi'), ('hin+eng', 'English Hindi')], max_length=10),
        ),
    ]
